{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vnpt.smartca.module.vnpt_smartca_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.syncfusion.flutter.pdfviewer",
          "module": "syncfusion_flutter_pdfviewer_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "appmire.be.flutterjailbreakdetection",
          "module": "flutter_jailbreak_detection_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 24808764,
          "sha512": "174f6ff195d728ef7c9fd9347d2d4196f5f11f8495db870c59320e648d46d65725518a5fac4f240abc4da94674b0e4458e16f0ff87349715eec097536edfeee1",
          "sha256": "58307323cbef5b896135e63932c6e456ac22a003ee16092cdc25bafe0406091d",
          "sha1": "e427153acaf299d81c7cb248235114764c2fe447",
          "md5": "ca0d6ce275e19b4f70a48d958aaff377"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.syncfusion.flutter.pdfviewer",
          "module": "syncfusion_flutter_pdfviewer_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.deviceinfo",
          "module": "device_info_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.localauth",
          "module": "local_auth_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "appmire.be.flutterjailbreakdetection",
          "module": "flutter_jailbreak_detection_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 24808764,
          "sha512": "174f6ff195d728ef7c9fd9347d2d4196f5f11f8495db870c59320e648d46d65725518a5fac4f240abc4da94674b0e4458e16f0ff87349715eec097536edfeee1",
          "sha256": "58307323cbef5b896135e63932c6e456ac22a003ee16092cdc25bafe0406091d",
          "sha1": "e427153acaf299d81c7cb248235114764c2fe447",
          "md5": "ca0d6ce275e19b4f70a48d958aaff377"
        }
      ]
    }
  ]
}
